apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode-web
  labels:
    app: hdfs-namenode-web
spec:
  type: NodePort
  ports:
  - port: 8020
    nodePort: 30020
    name: fs
  - port: 50070
    nodePort: 30070
    name: webui
  selector:
    app: hdfs-namenode