apiVersion: v1
kind: Service
metadata:
  name: yarn-rm-web
  labels:
    app: yarn-rm-web
spec:
  type: NodePort
  ports:
  - port: 8088
    nodePort: 30088
    name: webui
  - port: 8032
    nodePort: 30032
    name: rm
  selector:
    app: yarn-rm